apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      name: hello
      labels:
        app: hello
    spec:
      containers:
      - name: hello-world
        # This is the import path for the Go project Dockerhub image to build and run.
        image: yusufkaratoprak/kubernetes-gosample3:latest
        ports:
        - containerPort: 8091
